sonata_block:
  default_contexts: [cms]
  blocks:
    # Enable the SonataAdminBundle block
    sonata.admin.block.admin_list:
      contexts:  [admin]
    sonata.user.block.menu:  # used to display the menu in profile pages
    sonata.user.block.account: # used to display menu option (login option)
    sonata.block.service.text: # used to if you plan to use Sonata user routes
    
sonata_user:
  #security_acl: true # Uncomment for ACL support
  manager_type: orm # can be orm or mongodb
  
fos_user:
  db_driver:  orm # can be orm or odm
  firewall_name:  main
  user_class:  Application\Sonata\UserBundle\Entity\User
  #user_class:  Sonata\UserBundle\Entity\BaseUser

  group:
    group_class:  Application\Sonata\UserBundle\Entity\Group
    #group_class:  Sonata\UserBundle\Entity\BaseGroup
    group_manager: sonata.user.orm.group_manager  

  service:
    user_manager: sonata.user.orm.user_manager  